version: '3'
services:
  db:
    container_name: db
    restart: always
    ports:
       - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:14.5-alpine
  # bot:
  #   container_name: bot
  #   depends_on:
  #     - db
  #   build:
  #     context: ./bot
  #   restart: on-failure
  #   ports:
  #     - ${PORT_BACK}:${PORT_BACK}
  #   env_file: .env
  #   networks:
  #     - milkyway
# networks:
#   milkyway:
#     driver: bridge
