version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    ports:
       - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:14.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
  prisma:
    depends_on:
      - postgres
    container_name: prisma
    build:
      context: ./prisma
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT_PRISMA}:${PORT_PRISMA}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - prisma:/prisma
  bot:
    container_name: bot
    depends_on:
      - postgres
      - prisma
    build:
      context: ./bot
    restart: on-failure
    env_file: .env
    volumes:
      - ./bot/src/:/bot/src/
      - prisma:/prisma
  server:
    container_name: server
    depends_on:
      - postgres
      - prisma
    build:
      context: ./server
    ports:
      - 3000:3000
    restart: on-failure
    env_file: .env
    volumes:
      - ./server/src/:/server/src/
      - prisma:/prisma
volumes:
  pgdata:
  prisma:
