version: '3'
services:
  db:
    container_name: db
    ports:
       - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:14.5-alpine
  node:
    container_name: bot
    build:
      context: .
    restart: on-failure
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    env_file: .env
    networks:
      - milkyway
networks:
  milkyway:
    driver: bridge
